  name: Setup Node.js environment
  uses: actions/setup-node@v3.6.0
  with:
    always-auth: # optional, default is false
    node-version: # optional
    node-version-file: # optional
    architecture: # optional
    check-latest: # optional
    registry-url: # optional
    scope: # optional
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    cache: # optional
    cache-dependency-path: # optional
